################################# Url settings #################################
baseurl: /stoptheworld
#baseurl: ""
#url: https://stoptheworld.github.io


################################# Site settings #################################
name: Stop The World
description: 假如生活欺骗了你，不要悲伤，不要哭泣。
motto: 我们笑着说再见，却深知再见遥遥无期。
banner: 我想带你去看绚丽的山峦，去看秀丽的溪谷，这份心情，人类是如何称呼的呢。
paginate: 5
paginate_path: "page:num"


################################# Page settings #################################
excerpt_separator:  '<!-- more -->' #文章摘要
permalink: /:year/:month/:day/:title/
#permalink: /:categories/:year/:month/:day/:title/


################################# Contact #################################
author: ZJL
github: https://github.com/stoptheworld/


################################# Global #################################
plugins: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown

#FB:
#  comments :
#    provider : disqus
#    disqus :
#        short_name : zhengjinglong